version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eportal
    expose:
      - "5432"
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
