version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eportal
    expose:
      - "5432"
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static/
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 eportal.wsgi:application
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
