# Generated by Django 4.2.3 on 2023-07-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('pdf_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftable',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_table', to='agent.agent'),
            preserve_default=False,
        ),
    ]
