# Generated by Django 4.2.3 on 2023-07-07 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
