# Generated by Django 4.2.3 on 2023-07-12 06:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAgent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.UUIDField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('pdf_cv_file', models.FileField(upload_to='pdf-cv')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=100, null=True)),
                ('skills', models.JSONField(null=True)),
                ('college_name', models.CharField(max_length=250, null=True)),
                ('degree', models.CharField(max_length=250, null=True)),
                ('designation', models.CharField(max_length=250, null=True)),
                ('experience', models.CharField(max_length=250, null=True)),
                ('company_names', models.JSONField(null=True)),
                ('no_of_pages', models.IntegerField(null=True)),
                ('total_experience', models.IntegerField(null=True)),
                ('raw_data', models.TextField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_agent', to='agent.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
