# Generated by Django 4.2.3 on 2023-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfagent',
            name='college_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='designation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='mobile_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
