# Generated by Django 3.2.19 on 2023-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfagent',
            name='pdf_cv_file',
            field=models.FileField(default=None, upload_to='pdf-cv'),
            preserve_default=False,
        ),
    ]
