# Generated by Django 4.2.3 on 2023-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_pdfagent_pdf_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfagent',
            name='college_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='company_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='degree',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='designation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='experience',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='no_of_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='raw_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='skills',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pdfagent',
            name='total_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='pdf_cv_file',
            field=models.TextField(null=True),
        ),
    ]
