# Generated by Django 4.2.3 on 2023-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_pdfagent_college_name_pdfagent_company_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfagent',
            old_name='mobile',
            new_name='mobile_number',
        ),
        migrations.AlterField(
            model_name='pdfagent',
            name='pdf_cv_file',
            field=models.FileField(default=None, upload_to='pdf-cv'),
            preserve_default=False,
        ),
    ]
