# Generated by Django 4.2.3 on 2023-07-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agent_batches_remove_agent_name_and_more'),
        ('pdf', '0005_alter_pdfagent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfagent',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
            preserve_default=False,
        ),
    ]
