# Generated by Django 4.2.3 on 2023-07-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agent_batches_remove_agent_name_and_more'),
        ('pdf', '0006_pdfagent_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_agent', to='agent.agent'),
        ),
    ]
